### ISSUE TITLE
why stop here and nothing happened

### ISSUE THREAD

**Issue by kas0n** [bats3c/ADCSPwn#2]
Nice work bro!
But why stop here and nothing happened?
![image](https://user-images.githubusercontent.com/42311185/127760560-7e0fa2fd-c40d-423e-95dd-a854dabe1293.png)

**Comment by bats3c** [comment]
If you are triggering it remotely, you will need to ensure the WebClient service is running on the remote machine.

I'll be releasing a blog post detailing a couple methods of doing this in the future, till then you can just use the `sc.exe` command.

**Comment by RoxanaKovaci** [comment]
I thought, by default, the WebClient service is not installed on servers? As you're coercing auth from a DC ...

**Comment by Pretexts** [comment]
？
