### ISSUE TITLE
ERROR EXECUTE

### ISSUE THREAD

**Issue by salinnsilva** [bats3c/ADCSPwn#4]
ADCSPwn.exe --adcs barcelona12.dc.nova --remote 192.168.172.129 --output C:\Temp\cert_b64.txt

The local computer is not part of a domain or the domain cannot be contacted.
even with everything right and connected

my computer is pt-br -> The local computer is not part of a domain or the domain cannot be contacted.
![image](https://user-images.githubusercontent.com/86507580/127957540-c6275da7-7346-4b1e-9f38-ffaeca5cbca5.png)

**Comment by bats3c** [comment]
For obvious reasons this attack will only work from AD connected machines :facepalm:
